fastcampus-febe/TeamA-BE

src/main/java/com/example/travel/controller/PageController.java
=> 11 - 게시판 페이지로 이동

appspec.yml, build.gradle, scripts/start.sh, scripts/stop.sh
=> 13 - AWS 배포

src/main/java/com/example/travel/controller/BoardController.java, src/main/java/com/example/travel/dto/BoardRequestDto.java, src/main/java/com/example/travel/dto/BoardResponseDto.java, src/main/java/com/example/travel/entity/Board.java, src/main/java/com/example/travel/entity/Comment.java, src/main/java/com/example/travel/exception/CustomException.java, src/main/java/com/example/travel/exception/ErrorCode.java, src/main/java/com/example/travel/exception/ErrorResponse.java, src/main/java/com/example/travel/exception/GlobalExceptionHandler.java, src/main/java/com/example/travel/repository/BoardRepository.java, src/main/java/com/example/travel/service/BoardService.java, src/test/java/com/example/travel/controller/BoardControllerTest.java
=> 18 - Board추가

src/main/java/com/example/travel/config/WebSecurityConfig.java, src/main/java/com/example/travel/controller/BoardController.java, src/main/java/com/example/travel/service/BoardService.java, src/test/java/com/example/travel/controller/BoardControllerTest.java
[GetMapping] : /board/{id}
게시글 index 번호를 통해 db에서 select 해온다.
로그인을 하지 않아도 /board/** 경로들은 권한 검사 안하도록 임시로 설정 해두었음. (WebSecurityConfig)
=> #19 - 게시판 > 상세 게시글 내용 가져오기

src/main/java/com/example/travel/entity/Board.java, src/main/java/com/example/travel/service/BoardService.java, src/main/resources/application.properties
=> 21 - 게시글 조회, 작성, 수정

src/main/java/com/example/travel/controller/BoardController.java, src/main/java/com/example/travel/service/BoardService.java, src/test/java/com/example/travel/controller/BoardControllerTest.java
=> #22-deleteBoard

src/main/java/com/example/travel/controller/BoardController.java, src/main/java/com/example/travel/dto/BoardRequestDto.java, src/main/java/com/example/travel/dto/BoardResponseDto.java, src/main/java/com/example/travel/entity/Board.java, src/main/java/com/example/travel/entity/Member.java, src/main/java/com/example/travel/entity/Thumb.java, src/main/java/com/example/travel/repository/ThumbRepository.java, src/main/java/com/example/travel/service/BoardService.java, src/test/java/com/example/travel/controller/BoardControllerTest.java
좋아요 기능은 추가 수정필요.
조회수는 기능구현 완료.
=> 26 - 좋아요 및 조회수

src/main/java/com/example/travel/entity/Board.java, src/main/java/com/example/travel/entity/Comment.java
Board, Comment 엔티티 수정 (추후 수정 할 수도 있음)
=> 30 - Entity수정

src/main/java/com/example/travel/dto/BoardResponseDto.java, src/main/java/com/example/travel/dto/CommentRequestDto.java, src/main/java/com/example/travel/dto/CommentResponseDto.java, src/main/java/com/example/travel/entity/Comment.java, src/main/java/com/example/travel/repository/CommentRepository.java
1. Comment 관련 response & request dto 생성
2. Comment 엔티티에 댓글 수정 메서드 추가
3. CommentRepository 생성
=> CommentDTO 추가

src/main/java/com/example/travel/controller/BoardController.java, src/main/java/com/example/travel/service/BoardService.java
=> 36 - 게시판오류수정

src/main/java/com/example/travel/service/CommentService.java
댓글 작성 시 wirter 컬럼에 null 로 입력되는 문제가 있어 user의 nickname 이 writer 컬럼에 저장 될 수 있도록 수정함.
=> #36-댓글 작성 시 writer 컬럼에 nickname 저장되도록 수정.

src/test/java/com/example/travel/TravelApplicationTests.java, src/test/java/com/example/travel/controller/BoardControllerTest.java
배포하는데 오류가 나서 test파일 내 annotation들을 삭제한다.
=> 41 - test파일어노테이션삭제

src/main/java/com/example/travel/repository/BoardRepository.java, src/main/java/com/example/travel/service/BoardService.java
작성자의 닉네임을 일부만 검색해도 해당 작성자의 댓글이 보여지도록 수정
=> 45 - findAllByWriterContaining

src/main/java/com/example/travel/dto/BoardResponseDto.java, src/main/java/com/example/travel/service/BoardService.java
게시글 작성시 DB에 작성자의 닉네임이 저장 안 되는 오류 수정
=> 46 - BoardWriter

build.gradle, src/main/java/com/example/travel/api/PlaceApi.java, src/main/java/com/example/travel/entity/Place.java, src/main/java/com/example/travel/repository/PlaceRepository.java, src/main/java/com/example/travel/service/PlaceService.java
한국관광공사 국문 관광정보 서비스 api 를 이용하여 관광지 공통 정보를 json 으로 응답 받아 db 에 저장하였다.
=> #47 - TourAPI를 통한 관광지 공통정보 가져오기

src/main/java/com/example/travel/controller/SearchController.java, src/main/java/com/example/travel/dto/PlaceRequestDto.java, src/main/java/com/example/travel/dto/PlaceResponseDto.java, src/main/java/com/example/travel/repository/PlaceRepository.java, src/main/java/com/example/travel/service/PlaceService.java
GET "/search/results?title=관광지명" 을 통해서 검색했을 때 place 의 title 컬럼과 비교하여 일치하는 데이터를 리스트로 보여준다.
=> Feature/#54 관광지명으로 검색 시 결과 리스트 보여주기

build.gradle, src/main/java/com/example/travel/controller/WeatherApiController.java
=> 56 - weatherAPI

src/main/java/com/example/travel/api/KakaoMapApi.java
=> 57 - kakaoMapAPI

src/main/java/com/example/travel/controller/ReviewController.java, src/main/java/com/example/travel/dto/ReviewRequestDto.java, src/main/java/com/example/travel/dto/ReviewResponseDto.java, src/main/java/com/example/travel/entity/Place.java, src/main/java/com/example/travel/entity/Review.java, src/main/java/com/example/travel/repository/ReviewRepository.java, src/main/java/com/example/travel/service/ReviewService.java
=> 60 - reviewCRUD

src/main/java/com/example/travel/controller/MemberController.java, src/main/java/com/example/travel/dto/PasswordDto.java, src/main/java/com/example/travel/entity/Member.java, src/main/java/com/example/travel/service/MemberService.java
changes
1. 마이페이지 회원정보 조회
2. 마이페이지 회원 탈퇴
3. 회원 비밀번호 변경 
기능 추가하였습니다.
감사합니다.
드디어 4개ㅠㅠ
=> feat: ryusun-비밀번호변경&마이페이지 구현

src/main/java/com/example/travel/controller/SearchController.java, src/main/java/com/example/travel/dto/PlaceRequestDto.java, src/main/java/com/example/travel/dto/PlaceResponseDto.java, src/main/java/com/example/travel/entity/Favor.java, src/main/java/com/example/travel/entity/Place.java, src/main/java/com/example/travel/repository/FavorRepository.java, src/main/java/com/example/travel/repository/PlaceRepository.java, src/main/java/com/example/travel/service/PlaceService.java
- 특정 관광지에 대한 찜 기능(찜 취소하기도 동일)
- 관광지 상세 정보에서 해당 유저의 찜 여부 확인 가능(로그인하지 않은 유저는 관광지 상세정보만 열람 가능)
- 관광지 리스트업 되는 페이지에서 해당 관광지에 대한 찜 cnt 합계도 보여줄 것.
- swagger copy & paste 하느라 제대로 기능 설명하지 못한 부분 추후 수정 예정입니다.(죄송합니다...)
=> #62 - 찜 기능

src/main/java/com/example/travel/controller/SearchController.java, src/main/java/com/example/travel/repository/FavorRepository.java, src/main/java/com/example/travel/service/PlaceService.java
각 관광지의 찜 횟수를 확인 할 수 있도록 추가하였다.
=> #66 - 관광지 검색 결과 리스트에 각 관광지에 대한 찜 카운트 합계 추가

src/main/java/com/example/travel/controller/MemberController.java, src/main/java/com/example/travel/dto/FavorResponseDto.java, src/main/java/com/example/travel/repository/FavorRepository.java, src/main/java/com/example/travel/repository/ReviewRepository.java, src/main/java/com/example/travel/service/MemberService.java
Changes
1. 마이페이지에서 회원의 찜 목록 조회
2. 마이페이지에서 회원의 리뷰 목록 조회
기능 추가하였습니다.
감사합니다람쥐~
=> 69. feat:ryusun-마이페이지 찜목록&리뷰목록

src/main/java/com/example/travel/controller/SearchController.java, src/main/java/com/example/travel/dto/PlaceResponseDto.java, src/main/java/com/example/travel/service/PlaceService.java
Changes
1. 상세페이지내 날씨 정보 추가하였습니다.
감사합니당🥰
=> 91.feat:ryusun - 상세페이지내 날씨 정보 추가

src/main/java/com/example/travel/controller/BoardController.java, src/main/java/com/example/travel/controller/PageController.java
1. BoardController에 게시글 좋아요 url 수정
2. PageController에 게시판 작성 페이지 접근 url 추가
=> 73 - url수정

src/main/java/com/example/travel/dto/PlaceResponseDto.java, src/main/java/com/example/travel/repository/CommentRepository.java, src/main/java/com/example/travel/repository/ReviewRepository.java, src/main/java/com/example/travel/service/CommentService.java, src/main/java/com/example/travel/service/PlaceService.java, src/main/java/com/example/travel/service/ReviewService.java
Changes
1. 댓글 삭제시 게시글 삭제되는 오류 수정하였습니다.
2. 특정 댓글 조회시 다른 게시글 댓글 반환되는 오류 수정하였습니다.
3. 2. 특정 리뷰 조회시 다른 게시글 리뷰 반환되는 오류 수정하였습니다.
4. 상세페이지내 날씨 조회 오류 수정하였습니다.
감사합니당😊🍻🍗
=> 74.fix:ryusun - 다수 오류 수정

src/main/java/com/example/travel/controller/ReviewController.java, src/main/java/com/example/travel/dto/PlaceReviewResponseDto.java, src/main/java/com/example/travel/repository/ReviewRepository.java, src/main/java/com/example/travel/service/PlaceService.java, src/main/java/com/example/travel/service/ReviewService.java
리뷰 가장 많은 관광지 10 곳을 보여준다.
리뷰 테이블이 없는 경우에는 place 테이블의 id 기준 오름차순으로 관광지 10 곳을 보여준다.
=> #75 - 리뷰 많은 순 관광지 10곳 리스트

src/main/java/com/example/travel/controller/BoardController.java, src/main/java/com/example/travel/service/BoardService.java
=> 78 - BoardPagination

src/main/java/com/example/travel/config/WebSecurityConfig.java, src/main/java/com/example/travel/controller/SearchController.java
권한검사 필요 없는 url 추가하였음.
관광지 상세정보 (GET "place/{id}") 접근 시 인증 정보 없는 경우 NPE 발생하여 해당 부분 수정함.
=> #81 - WebSecurityConfig 권한 검사 url 수정

src/main/java/com/example/travel/controller/BoardController.java, src/main/java/com/example/travel/dto/BoardRequestDto.java, src/main/java/com/example/travel/dto/BoardResponseDto.java, src/main/java/com/example/travel/entity/Board.java, src/main/java/com/example/travel/service/BoardService.java
=> 87 - Board수정

src/main/java/com/example/travel/config/WebSecurityConfig.java
WebSecurityConfig에서 PUBLIC_URLS에 "/logout" 추가
=> 89 - Logout수정

README.md, src/main/java/com/example/travel/config/WebSecurityConfig.java
WebSecurityConfig에서 logout이 중복이라 다시 삭제하고 보냅니다.
=> Feature/91 logout중복

src/main/java/com/example/travel/config/WebSecurityConfig.java
=> #92 - WebSecurityConfig 수정
